services:
  web:
    image: 'mastodon-staging:${MASTODON_IMAGE_TAG:?MASTODON_IMAGE_TAG is required}'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MASTODON_VERSION_METADATA: dks
        SOURCE_COMMIT: '${MASTODON_SOURCE_COMMIT:?MASTODON_SOURCE_COMMIT is required}'

  streaming:
    image: 'mastodon-staging-streaming:${MASTODON_IMAGE_TAG:?MASTODON_IMAGE_TAG is required}'
    build:
      context: .
      dockerfile: streaming/Dockerfile
      args:
        MASTODON_VERSION_METADATA: dks

  sidekiq:
    image: 'mastodon-staging:${MASTODON_IMAGE_TAG:?MASTODON_IMAGE_TAG is required}'
